#
###################################
# Site wide configuration
####################################
#
title: amodrono's blog
email:
description: amodrono's simple blog.
url: # the base hostname & protocol for your site
keywords: ["blog", "cydia", "ios", "jailbreak", "programming", "C++", "C", "Python", "Swift", "Objective-C"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Madrid
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: amodrono
  avatar: amodrono.png
  job: "Proud Spanish Programmer"
  bio: "JavaScript, C, C++, Swift, Objective-C, and Python developer. Aspiring computer science and software engineer. 🇪🇸"
  email:
  disqus-shortname:
  twitter: Semiak_
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: iAlex11
  gitlab: Semiak
  stackoverflow: 9647800/ialex11   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: alex16mvr
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
